"""add message_id field to posts table

Revision ID: 20d373dbf73c
Revises: 1ad2871e2c84
Create Date: 2024-08-02 10:20:34.649228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20d373dbf73c"
down_revision: Union[str, None] = "1ad2871e2c84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("message_id", sa.BigInteger(), nullable=True)
    )
    op.create_unique_constraint(None, "posts", ["message_id"])
    op.alter_column(
        "users",
        "subscription_expiration_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "subscription_expiration_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "posts", type_="unique")
    op.drop_column("posts", "message_id")
    # ### end Alembic commands ###
