"""create posts table | add relations on user to post

Revision ID: a22f09c4fa41
Revises: 9ebca264bc97
Create Date: 2024-07-30 06:48:21.679120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a22f09c4fa41"
down_revision: Union[str, None] = "9ebca264bc97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("name", sa.String(length=35), nullable=False),
        sa.Column("product", sa.String(length=35), nullable=False),
        sa.Column("products_count", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("city", sa.String(length=25), nullable=False),
        sa.Column("is_delivery_company", sa.String(), nullable=False),
        sa.Column("comment", sa.String(length=140), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=False),
        sa.Column("telegram_username", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
